import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Modal, Web3ModalProvider } from "../context/Web3Modal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Web3ModalProvider>{children}</Web3ModalProvider>
      </body>
    </html>
  );
}
